# Generated by Django 5.1.1 on 2024-09-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='categories.category'),
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
